---
abstract: 'REST search platform'
author:
  - 'Peter Karman, C<< <karman at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: http://dev.perl.org/licenses/
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dezi
no_index:
  directory:
    - inc
    - t
recommends:
  LucyX::Suggester: 0.003
requires:
  Lucy: 0.003002
  Module::Load: 0.22
  Plack: 0
  Plack::Middleware::Auth::Basic: 0
  Plack::Middleware::ReverseProxy: 0
  SWISH::Prog: 0.64
  Search::OpenSearch: 0.23
  Search::OpenSearch::Engine::Lucy: 0.13
  Search::OpenSearch::Server: 0.21
  Search::Query: 0.21
  Search::Query::Dialect::Lucy: 0.05
  Test::More: 0
  perl: 5.8.3
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dezi
  homepage: https://github.com/karpet/Dezi
  license: http://opensource.org/licenses/gpl-license.php
  repository: http://github.com/karpet/Dezi
version: 0.002005
